import fs from "node:fs";
import path from "node:path";
import { type Product } from "../src/types/product";

const imageFolderPath = "public/images/all"; // Path to the folder containing your JPG files
const outputArray: Product[] = [];

fs.readdir(imageFolderPath, (err, files) => {
	if (err) {
		console.error(err);
		return;
	}

	// Loop through the files and create objects for each
	files.forEach((fileName) => {
		if (fileName.endsWith(".jpg")) {
			const imageUrl = path.join(imageFolderPath, fileName);
			const description = "Sample description"; // fileName.description
			const name = "Golden nebula"; // Remove the file extension
			const category = "Collar";
			const price = "150.000"; // fileName.price

			const imageObject: Product = {
				imageName: imageUrl,
				description,
				name,
				category,
				price,
			};

			outputArray.push(imageObject);
		}
	});
});

export const data: Product[] = [
	{
		imageName: "./images/all/image-01.jpg",
		category: "Collar",
		description: "description 01",
		name: "Golden Nebula",
		price: "150.000",
	},
	{
		imageName: "./images/all/image-02.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-03.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-04.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-05.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-06.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-07.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-08.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-09.jpg",
		category: "Areta",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-10.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-11.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-12.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-13.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-14.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-15.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-16.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-17.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-18.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-19.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-20.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-21.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-22.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-23.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-24.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-25.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-26.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-27.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-28.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-29.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-30.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-31.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-32.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-33.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-34.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-35.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-36.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-37.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-38.jpeg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-39.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-40.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-41.jpeg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-42.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-43.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-44.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-45.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-46.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-47.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-48.jpg",
		category: "Areta",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-49.jpeg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-50.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-51.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-52.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-53.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-54.jpeg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-55.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-56.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-57.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-58.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-59.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-60.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-61.jpg",
		category: "Areta",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-62.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-63.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-64.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-65.png",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-66.jpg",
		category: "Areta",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-67.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-68.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-69.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-70.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-71.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-72.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-73.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-74.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-75.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-76.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-77.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-78.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-79.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-80.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-81.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-82.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-83.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-84.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-85.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-86.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-87.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-88.jpg",
		category: "Brazalete",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-89.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/all/image-90.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
];

export default outputArray;

// export const data = [
// 	{
// 		imageName: "./images/all/image-01.jpg",
// 		description: "image 01",
// 		name: "Brazalete 01",
// 		category: "Brazalete",
// 		price: 150,
// 	},
// 	{
// 		imageName: "./images/all/image-02.jpg",
// 		description: "image 01",
// 		name: "Brazalete 01",
// 		category: "Brazalete",
// 		price: 150,
// 	},
// 	{
// 		imageName: "./images/all/image-03.jpg",
// 		description: "image 01",
// 		name: "Brazalete 01",
// 		category: "Brazalete",
// 		price: 150,
// 	},
// ];
